// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtHUf3s1bOgHGCmUwoVNfCpDf_6dL4R3M',
    appId: '1:505621514518:web:4a9afe1efc22e18305a837',
    messagingSenderId: '505621514518',
    projectId: 'fitapp-ade30',
    authDomain: 'fitapp-ade30.firebaseapp.com',
    storageBucket: 'fitapp-ade30.appspot.com',
    measurementId: 'G-FZ8TH773ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9IAyiJj36bv1VX7lM-UCQMcCFRx5ti0',
    appId: '1:505621514518:android:aa217e42d9b7e51d05a837',
    messagingSenderId: '505621514518',
    projectId: 'fitapp-ade30',
    storageBucket: 'fitapp-ade30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_O09o5JrqjA_K32AeOgglF7haOnaW5Qc',
    appId: '1:505621514518:ios:9d9fa724de0f065705a837',
    messagingSenderId: '505621514518',
    projectId: 'fitapp-ade30',
    storageBucket: 'fitapp-ade30.appspot.com',
    iosBundleId: 'com.fitapp.fitapp',
  );
}
